### Load Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load Data

In [2]:
path = "https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)

In [3]:
df

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                             0                    0   
4

### Split Data

In [4]:
X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [5]:
X

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0          1672.0    3     8971.291866   
1      3.0      3.0          1750.0    3     8514.285714   
2      3.0      2.0          1750.0    3     8571.428571   
3      2.0      2.0          1250.0    2     3200.000000   
4      2.0      2.0          1200.0    2     6916.666667   
...    ...      ...             ...  ...             ...   
7115   3.0      2.0          2900.0    3    11206.896552   
7116   3.0      1.0          1780.0    3     4765.730337   
7117   2.0      1.0           880.0    2     5454.545455   
7118   2.0      1.0          1000.0    2     5500.000000   
7119   2.0      1.0          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                       0                           1                    0   
1                       0                           1                    0   
2                       0                           1                    0   
3                       0                           1                    0   
4                       1                           1                    0   
...                   ...                         ...                  ...   
7115                    0                           1                    0   
7116                    0                           0                    0   
7117                    1                           1                    0   
7118                    1                           0                    0   
7119                    1                           0                    0   

      ...  location_Kalena Agrahara  location_Horamavu Agara  \
0     ...                         0                        0   
1     ...                         0                        0   
2     ...                         0                        0   
3     ...                         0                        0   
4     ...                         0                        0   
...   ...                       ...                      ...   
7115  ...                         0                        0   
7116  ...                         0                        0   
7117  ...                         0                        0   
7118  ...                         0                        0   
7119  ...                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1            

In [6]:
y

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...  
7115    325.00
7116     84.83
7117     48.00
7118     55.00
7119     78.00
Name: price, Length: 7120, dtype: float64

# Split Data into Train-Test

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [8]:
X_train

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
7112   5.0      2.0          2500.0    6     7400.000000   
2169   2.0      0.0           995.0    2     4623.115578   
47     2.0      2.0          1180.0    2     7500.000000   
446    2.0      1.0          1450.0    3     5862.068966   
2650   2.0      1.0          1197.0    2     6432.748538   
...    ...      ...             ...  ...             ...   
6672   2.0      1.0          1246.0    2     5457.463884   
1733   2.0      1.0          1010.0    2     5742.574257   
1760   2.0      2.0          1080.0    2     4629.629630   
485    2.0      2.0           982.0    2     2500.000000   
2105   2.0      1.0          1000.0    2     2888.000000   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
7112                              0                        1   
2169                              0                        1   
47                                1                        0   
446                               1                        0   
2650                              1                        0   
...                             ...                      ...   
6672                              1                        0   
1733                              0                        1   
1760                              1                        0   
485                               1                        0   
2105                              1                        0   

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
7112                    0                           1                    0   
2169                    0                           1                    0   
47                      0                           1                    0   
446                     0                           1                    0   
2650                    0                           1                    0   
...                   ...                         ...                  ...   
6672                    0                           1                    0   
1733                    0                           1                    0   
1760                    0                           1                    0   
485                     0                           0                    0   
2105                    0                           0                    0   

      ...  location_Kalena Agrahara  location_Horamavu Agara  \
7112  ...                         0                        0   
2169  ...                         0                        0   
47    ...                         0                        0   
446   ...                         0                        0   
2650  ...                         0                        0   
...   ...                       ...                      ...   
6672  ...                         0                        0   
1733  ...                         0                        0   
1760  ...                         0                        0   
485   ...                         0                        0   
2105  ...                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
7112                        0                       0   
2169                        0                       0   
47                          0                       0   
446                         0                       0   
2650                        0                       0   
...                       ...                     ...   
6672                        0                       0   
1733                        0                       0   
1760                        0                       0   
485                         0                       0   
2105                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
7112                          0                    0   
2169         

### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 3.0245515 ,  0.55008644,  1.33396246, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 , -0.60737352, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.36873754, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-0.44274597,  0.55008644, -0.49772996, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.62414253, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.6009239 , ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [11]:
X_test

array([[ 0.71301986,  0.0112734 ,  0.30202307, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.58028511, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [ 1.86878568,  0.55008644,  0.62450413, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-1.59851179,  0.55008644, -1.03304852, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.38550655, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 ,  0.12917322, ..., -0.05630391,
        -0.05630391, -0.05138463]])

## Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.7903837092682249

# Support Vector Regression

In [13]:
from sklearn.svm import SVR
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train, y_train)
svr_linear.score(X_test, y_test)

0.7962740979067113

# Random Forest Regression 

In [14]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train, y_train)  
regressor.score(X_test,y_test)

0.8821995118915241

# Decision Tree Regressor

In [15]:
from sklearn.tree import DecisionTreeRegressor 
regressor = DecisionTreeRegressor(random_state = 1) 
regressor.fit(X, y)
regressor.score(X_test,y_test)

-0.4208201538193985

## Predict the value of Home and Test

In [16]:
X_test[0, :]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [17]:
lr.predict([X_test[0, :]])

array([76.90661876])

In [18]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [19]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [21]:
y_pred = svr_linear.predict(X_test)
y_pred

array([ 86.53631232,  33.7037173 , 122.48422547, ...,  26.24020737,
        64.52576739, 176.17735697])

In [22]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  4093.451698511198
RMSE =  63.98008829715069
